ignore:
  - "AmplifyTests"
  - "AmplifyPlugins/Analytics/AmplifyFunctionalTests"
  - "AmplifyPlugins/Analytics/AmplifyTestApp"
  - "AmplifyPlugins/Analytics/AmplifyTestCommon"
  - "AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginIntegrationTests"
  - "AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests"
  - "AmplifyPlugins/API/AWSAPICategoryPluginGraphQLAPIKeyIntegrationTests"
  - "AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests"
  - "AmplifyPlugins/API/AWSAPICategoryPluginTestCommon"
  - "AmplifyPlugins/API/AWSAPICategoryPluginTests"
  - "AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests"
  - "AmplifyPlugins/Auth/AWSCognitoAuthPluginTests"
  - "AmplifyPlugins/Core/AWSPluginsCoreTests"
  - "AmplifyPlugins/Core/AWSPluginsTestCommon"
  - "AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests"
  - "AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests"
  - "AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests"
  - "AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests"
  - "AmplifyPlugins/Predictions/AWSPredictionsPluginTests"
  - "AmplifyPlugins/Predictions/CoreMLPredictionsPluginIntegrationTests"
  - "AmplifyPlugins/Predictions/CoreMLPredictionsPluginTests"
  - "AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests"
  - "AmplifyPlugins/Storage/AWSS3StoragePluginTests"
  